server:
  port: 9999
  servlet:
    context-path: /wear_shop/api
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 2KB
    tomcat:
      connection-timeout: 600000
  feign:
    client:
      config:
        default:
          connectTimeout: 600000
          readTimeout: 600000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wear_shop?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: 123123qweA
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      pool-name: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    show-sql: false
app:
  uploadFileDir: E:\wear copation\upload
  uploadFileDir2: E:\wear copation\New folder\sb-admin-2-vue\src\assets
  uploadFileDir3: E:\wear copation\frontEnd\shipit\src\assets